### ISSUE TITLE
PHP Version Support (MyBB and PHP Team)

### ISSUE THREAD

**Issue by euantorano** [mybb/blog.mybb.com-drafts#6]
During a discussion on Discord, it was mentioned that we should look at changing the minimum PHP version requirements. This caused a bit of an argument, and it became clear that not everybody is aware of the PHP versions that MyBB 1.8 currently supports, what versions of PHP the PHP team currently support and provide patches for and what the differences are between versions.

Due to this, it might be a good idea to write a blog post detailing which versions of PHP are currently officially supported by the PHP team, when support for common version will end (or in the case of older versions, did end), and what advantages newer versions have.

It may also be a good idea to create blog posts as PHP versions reach EOL with the PHP team warning users of this fact as the average administrator may not be aware of this.

**Comment by kawaii** [comment]
I've made a start on this today, but it's not ready yet. I'll likely open a PR tomorrow.

**Comment by kawaii** [comment]
Pleased see the attached PR. :blush:
