### ISSUE TITLE
MyBB Docker Blog Post

### ISSUE THREAD

**Issue by kawaii** [mybb/blog.mybb.com-drafts#7]
Someone (me) needs to write a blog post regarding the recent creation of the MyBB Dockerfile and Docker Compose recipe. I will submit a PR for review later since I more or less created the project.

https://github.com/mybb/docker-compose

**Comment by kawaii** [comment]
Please see the PR that I have created, which contains a draft of the proposed blog post. :slightly_smiling_face:

**Comment by dvz** [comment]
Since the post introduces Docker, we can add a word about its use in the package builder that will be published later on.

**Comment by euantorano** [comment]
The hope is to also add some documentation pages explaining some common uses of Docker for testing PRs and verifying issues and such.
